// Local board game database
// Fields: id, name, year, rating (/10), minPlayers, maxPlayers, genre, length, complexity (BGG weight 1–5)
module.exports = [
  // ── Gateway / Family ──────────────────────────────────────────
  { id: 'catan',               name: 'Catan',                                          year: 1995, rating: 7.2, minPlayers: 3, maxPlayers: 4,  genre: 'Family',          length: '60–120 min', complexity: 2.3 },
  { id: 'ticket-to-ride',      name: 'Ticket to Ride',                                 year: 2004, rating: 7.5, minPlayers: 2, maxPlayers: 5,  genre: 'Family',          length: '45–75 min',  complexity: 1.9 },
  { id: 'ticket-to-ride-eu',   name: 'Ticket to Ride: Europe',                         year: 2005, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Family',          length: '45–75 min',  complexity: 1.9 },
  { id: 'carcassonne',         name: 'Carcassonne',                                    year: 2000, rating: 7.4, minPlayers: 2, maxPlayers: 5,  genre: 'Family',          length: '30–45 min',  complexity: 1.9 },
  { id: 'pandemic',            name: 'Pandemic',                                       year: 2008, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '45 min',     complexity: 2.4 },
  { id: 'splendor',            name: 'Splendor',                                       year: 2014, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30 min',     complexity: 1.7 },
  { id: 'azul',                name: 'Azul',                                           year: 2017, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30–45 min',  complexity: 1.8 },
  { id: 'kingdomino',          name: 'Kingdomino',                                     year: 2016, rating: 7.3, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '15–30 min',  complexity: 1.2 },
  { id: 'smallworld',          name: 'Small World',                                    year: 2009, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Area Control',    length: '40–80 min',  complexity: 2.3 },
  { id: 'king-of-tokyo',       name: 'King of Tokyo',                                  year: 2011, rating: 7.2, minPlayers: 2, maxPlayers: 6,  genre: 'Family',          length: '30 min',     complexity: 1.5 },
  { id: 'takenoko',            name: 'Takenoko',                                       year: 2011, rating: 7.2, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '45 min',     complexity: 1.7 },
  { id: 'forbidden-island',    name: 'Forbidden Island',                               year: 2010, rating: 6.8, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '30 min',     complexity: 1.7 },
  { id: 'forbidden-desert',    name: 'Forbidden Desert',                               year: 2013, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '45 min',     complexity: 2.1 },
  { id: 'betrayal-house',      name: 'Betrayal at House on the Hill',                  year: 2004, rating: 7.1, minPlayers: 3, maxPlayers: 6,  genre: 'Thematic',        length: '60 min',     complexity: 2.7 },
  { id: 'betrayal-baldurs',    name: "Betrayal at Baldur's Gate",                      year: 2017, rating: 7.0, minPlayers: 3, maxPlayers: 6,  genre: 'Thematic',        length: '60 min',     complexity: 2.7 },
  { id: 'clue',                name: 'Clue',                                           year: 1949, rating: 5.8, minPlayers: 3, maxPlayers: 6,  genre: 'Family',          length: '45 min',     complexity: 1.5 },
  { id: 'risk',                name: 'Risk',                                           year: 1959, rating: 5.6, minPlayers: 2, maxPlayers: 6,  genre: 'Area Control',    length: '2–4 hrs',    complexity: 2.1 },
  { id: 'monopoly',            name: 'Monopoly',                                       year: 1935, rating: 4.5, minPlayers: 2, maxPlayers: 8,  genre: 'Family',          length: '2–4 hrs',    complexity: 1.7 },
  { id: 'scrabble',            name: 'Scrabble',                                       year: 1938, rating: 6.5, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '60–90 min',  complexity: 1.7 },
  { id: 'battleship',          name: 'Battleship',                                     year: 1967, rating: 4.8, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '30 min',     complexity: 1.1 },
  { id: 'tokaido',             name: 'Tokaido',                                        year: 2012, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Family',          length: '45 min',     complexity: 1.3 },
  { id: 'karuba',              name: 'Karuba',                                         year: 2015, rating: 7.1, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '30 min',     complexity: 1.5 },
  { id: 'spot-it',             name: 'Spot It! (Dobble)',                               year: 2009, rating: 6.8, minPlayers: 2, maxPlayers: 8,  genre: 'Party',           length: '15 min',     complexity: 1.0 },
  { id: 'bananagrams',         name: 'Bananagrams',                                    year: 2006, rating: 6.8, minPlayers: 1, maxPlayers: 8,  genre: 'Family',          length: '15 min',     complexity: 1.1 },

  // ── Mid-weight Euro ───────────────────────────────────────────
  { id: '7-wonders',           name: '7 Wonders',                                      year: 2010, rating: 7.7, minPlayers: 3, maxPlayers: 7,  genre: 'Euro Strategy',   length: '30 min',     complexity: 2.3 },
  { id: '7-wonders-duel',      name: '7 Wonders Duel',                                 year: 2015, rating: 8.1, minPlayers: 2, maxPlayers: 2,  genre: 'Euro Strategy',   length: '30 min',     complexity: 2.2 },
  { id: 'dominion',            name: 'Dominion',                                       year: 2008, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '30 min',     complexity: 2.4 },
  { id: 'agricola',            name: 'Agricola',                                       year: 2007, rating: 8.0, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '90–150 min', complexity: 3.6 },
  { id: 'agricola-all',        name: 'Agricola: All Creatures Big and Small',          year: 2012, rating: 7.8, minPlayers: 2, maxPlayers: 2,  genre: 'Euro Strategy',   length: '30 min',     complexity: 2.1 },
  { id: 'stone-age',           name: 'Stone Age',                                      year: 2008, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 2.2 },
  { id: 'puerto-rico',         name: 'Puerto Rico',                                    year: 2002, rating: 7.9, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.0 },
  { id: 'power-grid',          name: 'Power Grid',                                     year: 2004, rating: 7.9, minPlayers: 2, maxPlayers: 6,  genre: 'Euro Strategy',   length: '120 min',    complexity: 2.9 },
  { id: 'istanbul',            name: 'Istanbul',                                       year: 2014, rating: 7.5, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '40–60 min',  complexity: 2.1 },
  { id: 'five-tribes',         name: 'Five Tribes',                                    year: 2014, rating: 7.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '40–80 min',  complexity: 2.8 },
  { id: 'concordia',           name: 'Concordia',                                      year: 2013, rating: 8.0, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '90 min',     complexity: 2.9 },
  { id: 'orleans',             name: "Orléans",                                        year: 2014, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 2.9 },
  { id: 'viticulture',         name: 'Viticulture Essential Edition',                  year: 2015, rating: 8.1, minPlayers: 1, maxPlayers: 6,  genre: 'Euro Strategy',   length: '45–90 min',  complexity: 2.9 },
  { id: 'wingspan',            name: 'Wingspan',                                       year: 2019, rating: 8.1, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '40–70 min',  complexity: 2.4 },
  { id: 'wingspan-asia',       name: 'Wingspan: Asia',                                 year: 2022, rating: 7.8, minPlayers: 1, maxPlayers: 6,  genre: 'Euro Strategy',   length: '40–70 min',  complexity: 2.5 },
  { id: 'everdell',            name: 'Everdell',                                       year: 2018, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '40–80 min',  complexity: 2.8 },
  { id: 'cascadia',            name: 'Cascadia',                                       year: 2021, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–45 min',  complexity: 1.8 },
  { id: 'sagrada',             name: 'Sagrada',                                        year: 2017, rating: 7.3, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–45 min',  complexity: 1.9 },
  { id: 'patchwork',           name: 'Patchwork',                                      year: 2014, rating: 7.8, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '15–30 min',  complexity: 1.7 },
  { id: 'raiders-north-sea',   name: 'Raiders of the North Sea',                       year: 2015, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–80 min',  complexity: 2.2 },
  { id: 'quacks',              name: 'The Quacks of Quedlinburg',                      year: 2018, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '45–75 min',  complexity: 1.9 },
  { id: 'roll-galaxy',         name: 'Roll for the Galaxy',                            year: 2014, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45 min',     complexity: 2.9 },
  { id: 'race-galaxy',         name: 'Race for the Galaxy',                            year: 2007, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–60 min',  complexity: 3.0 },
  { id: 'arnak',               name: 'Lost Ruins of Arnak',                            year: 2020, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–120 min', complexity: 2.6 },
  { id: 'cartographers',       name: 'Cartographers',                                  year: 2019, rating: 7.6, minPlayers: 1, maxPlayers: 100,genre: 'Roll & Write',    length: '30–45 min',  complexity: 1.9 },
  { id: 'dune-imperium',       name: 'Dune: Imperium',                                 year: 2020, rating: 8.2, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 2.9 },
  { id: 'imhotep',             name: 'Imhotep',                                        year: 2016, rating: 7.2, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '40 min',     complexity: 1.9 },
  { id: 'tzolkin',             name: "Tzolk'in: The Mayan Calendar",                   year: 2012, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 3.1 },
  { id: 'gwt',                 name: 'Great Western Trail',                            year: 2016, rating: 8.2, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '75–150 min', complexity: 3.4 },
  { id: 'keyflower',           name: 'Keyflower',                                      year: 2012, rating: 7.9, minPlayers: 2, maxPlayers: 6,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.7 },
  { id: 'dice-forge',          name: 'Dice Forge',                                     year: 2017, rating: 7.2, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '45 min',     complexity: 2.1 },
  { id: 'village',             name: 'Village',                                        year: 2011, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 2.8 },
  { id: 'obsession',           name: 'Obsession',                                      year: 2018, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–90 min',  complexity: 2.4 },
  { id: 'underwater-cities',   name: 'Underwater Cities',                              year: 2018, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '80–150 min', complexity: 3.7 },
  { id: 'tapestry',            name: 'Tapestry',                                       year: 2019, rating: 7.4, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.0 },
  { id: 'ark-nova',            name: 'Ark Nova',                                       year: 2021, rating: 8.6, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–150 min', complexity: 3.7 },
  { id: 'heat',                name: 'Heat: Pedal to the Metal',                       year: 2022, rating: 8.0, minPlayers: 1, maxPlayers: 6,  genre: 'Racing',          length: '30–60 min',  complexity: 2.1 },
  { id: 'earth',               name: 'Earth',                                          year: 2023, rating: 7.8, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45–90 min',  complexity: 2.3 },
  { id: 'brass-birmingham',    name: 'Brass: Birmingham',                              year: 2018, rating: 8.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.9 },
  { id: 'brass-lancashire',    name: 'Brass: Lancashire',                              year: 2018, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.4 },
  { id: 'lorenzo',             name: 'Lorenzo il Magnifico',                           year: 2016, rating: 7.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.3 },
  { id: 'maracaibo',           name: 'Maracaibo',                                      year: 2019, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–150 min', complexity: 3.7 },
  { id: 'paleo',               name: 'Paleo',                                          year: 2020, rating: 7.7, minPlayers: 1, maxPlayers: 4,  genre: 'Cooperative',     length: '45–60 min',  complexity: 2.5 },
  { id: 'hansa-teutonica',     name: 'Hansa Teutonica',                                year: 2009, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45–90 min',  complexity: 2.7 },
  { id: 'hadara',              name: 'Hadara',                                         year: 2019, rating: 7.3, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45–75 min',  complexity: 2.2 },
  { id: 'my-city',             name: 'My City',                                        year: 2020, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Legacy',          length: '30 min',     complexity: 1.8 },
  { id: 'parks',               name: 'Parks',                                          year: 2019, rating: 7.5, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '30–60 min',  complexity: 2.1 },
  { id: 'meadow',              name: 'Meadow',                                         year: 2021, rating: 7.4, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–75 min',  complexity: 1.9 },
  { id: 'calico',              name: 'Calico',                                         year: 2020, rating: 7.7, minPlayers: 1, maxPlayers: 4,  genre: 'Abstract',        length: '30–45 min',  complexity: 1.9 },
  { id: 'harmonies',           name: 'Harmonies',                                      year: 2024, rating: 7.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–45 min',  complexity: 1.8 },
  { id: 'dorfromantik',        name: 'Dorfromantik: The Board Game',                   year: 2021, rating: 7.9, minPlayers: 1, maxPlayers: 6,  genre: 'Cooperative',     length: '30–90 min',  complexity: 1.5 },
  { id: 'architects-wk',       name: 'Architects of the West Kingdom',                 year: 2018, rating: 7.8, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–80 min',  complexity: 2.5 },
  { id: 'paladins-wk',         name: 'Paladins of the West Kingdom',                   year: 2019, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.2 },
  { id: 'viscounts-wk',        name: 'Viscounts of the West Kingdom',                  year: 2020, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 3.3 },
  { id: 'beyond-the-sun',      name: 'Beyond the Sun',                                 year: 2020, rating: 8.0, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.6 },
  { id: 'apiary',              name: 'Apiary',                                         year: 2023, rating: 7.8, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45–90 min',  complexity: 3.0 },
  { id: 'marco-polo',          name: 'The Voyages of Marco Polo',                      year: 2015, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '40–100 min', complexity: 3.1 },
  { id: 'yokohama',            name: 'Yokohama',                                       year: 2016, rating: 7.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 3.2 },
  { id: 'hallertau',           name: 'Hallertau',                                      year: 2020, rating: 7.8, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.4 },
  { id: 'fields-of-arle',      name: 'Fields of Arle',                                 year: 2014, rating: 7.9, minPlayers: 1, maxPlayers: 2,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.5 },
  { id: 'nusfjord',            name: 'Nusfjord',                                       year: 2017, rating: 7.7, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '20–100 min', complexity: 2.8 },
  { id: 'twilight-inscription', name: 'Twilight Inscription',                          year: 2022, rating: 7.5, minPlayers: 1, maxPlayers: 8,  genre: 'Roll & Write',    length: '90 min',     complexity: 3.1 },
  { id: 'acquire',             name: 'Acquire',                                        year: 1964, rating: 7.5, minPlayers: 2, maxPlayers: 6,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 2.1 },
  { id: 'ra',                  name: 'Ra',                                             year: 1999, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '45–60 min',  complexity: 2.4 },
  { id: 'el-grande',           name: 'El Grande',                                      year: 1995, rating: 7.9, minPlayers: 2, maxPlayers: 5,  genre: 'Area Control',    length: '60–90 min',  complexity: 3.3 },
  { id: 'modern-art',          name: 'Modern Art',                                     year: 1992, rating: 7.5, minPlayers: 3, maxPlayers: 5,  genre: 'Euro Strategy',   length: '45 min',     complexity: 2.2 },
  { id: 'innovation',          name: 'Innovation',                                     year: 2010, rating: 7.2, minPlayers: 2, maxPlayers: 4,  genre: 'Filler',          length: '30–60 min',  complexity: 2.9 },
  { id: 'oceans',              name: 'Oceans',                                         year: 2020, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–90 min',  complexity: 2.6 },
  { id: 'photosynthesis',      name: 'Photosynthesis',                                 year: 2017, rating: 7.3, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30–60 min',  complexity: 2.2 },
  { id: 'azul-queens',         name: "Azul: Queen's Garden",                           year: 2022, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30–60 min',  complexity: 2.0 },
  { id: 'turing-machine',      name: 'Turing Machine',                                 year: 2022, rating: 7.6, minPlayers: 1, maxPlayers: 4,  genre: 'Abstract',        length: '20 min',     complexity: 2.0 },
  { id: 'ingenious',           name: 'Ingenious',                                      year: 2004, rating: 7.2, minPlayers: 1, maxPlayers: 4,  genre: 'Abstract',        length: '45 min',     complexity: 1.5 },
  { id: 'point-salad',         name: 'Point Salad',                                    year: 2019, rating: 7.2, minPlayers: 2, maxPlayers: 6,  genre: 'Filler',          length: '15 min',     complexity: 1.2 },
  { id: 'galaxy-trucker',      name: 'Galaxy Trucker',                                 year: 2007, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '45–75 min',  complexity: 2.5 },
  { id: 'formula-d',           name: 'Formula D',                                      year: 2008, rating: 7.0, minPlayers: 2, maxPlayers: 10, genre: 'Racing',          length: '60 min',     complexity: 2.2 },

  // ── Heavy Strategy ────────────────────────────────────────────
  { id: 'gloomhaven',          name: 'Gloomhaven',                                     year: 2017, rating: 8.4, minPlayers: 1, maxPlayers: 4,  genre: 'Dungeon Crawl',   length: '60–120 min', complexity: 3.9 },
  { id: 'gloomhaven-jaws',     name: 'Gloomhaven: Jaws of the Lion',                   year: 2020, rating: 8.2, minPlayers: 1, maxPlayers: 4,  genre: 'Dungeon Crawl',   length: '60–90 min',  complexity: 3.7 },
  { id: 'frosthaven',          name: 'Frosthaven',                                     year: 2022, rating: 8.6, minPlayers: 1, maxPlayers: 4,  genre: 'Dungeon Crawl',   length: '60–120 min', complexity: 4.0 },
  { id: 'terraforming-mars',   name: 'Terraforming Mars',                              year: 2016, rating: 8.4, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.2 },
  { id: 'terra-mystica',       name: 'Terra Mystica',                                  year: 2012, rating: 8.1, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–150 min', complexity: 3.9 },
  { id: 'gaia-project',        name: 'Gaia Project',                                   year: 2017, rating: 8.4, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–150 min', complexity: 4.0 },
  { id: 'scythe',              name: 'Scythe',                                         year: 2016, rating: 8.2, minPlayers: 1, maxPlayers: 5,  genre: 'Area Control',    length: '90–115 min', complexity: 3.4 },
  { id: 'spirit-island',       name: 'Spirit Island',                                  year: 2017, rating: 8.4, minPlayers: 1, maxPlayers: 4,  genre: 'Cooperative',     length: '90–120 min', complexity: 4.0 },
  { id: 'twilight-imperium',   name: 'Twilight Imperium: Fourth Edition',              year: 2017, rating: 8.7, minPlayers: 3, maxPlayers: 6,  genre: 'Area Control',    length: '4–8 hrs',    complexity: 4.2 },
  { id: 'twilight-struggle',   name: 'Twilight Struggle',                              year: 2005, rating: 8.3, minPlayers: 2, maxPlayers: 2,  genre: 'Wargame',         length: '3 hrs',      complexity: 3.6 },
  { id: 'feast-for-odin',      name: 'A Feast for Odin',                               year: 2016, rating: 8.2, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 4.1 },
  { id: 'caverna',             name: 'Caverna: The Cave Farmers',                      year: 2013, rating: 8.0, minPlayers: 1, maxPlayers: 7,  genre: 'Euro Strategy',   length: '30–210 min', complexity: 3.7 },
  { id: 'le-havre',            name: 'Le Havre',                                       year: 2008, rating: 8.0, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '30–150 min', complexity: 3.4 },
  { id: 'mage-knight',         name: 'Mage Knight Board Game',                         year: 2011, rating: 8.1, minPlayers: 1, maxPlayers: 4,  genre: 'Thematic',        length: '2–4 hrs',    complexity: 4.5 },
  { id: 'robinson-crusoe',     name: 'Robinson Crusoe: Adventures on the Cursed Island', year: 2012, rating: 7.8, minPlayers: 1, maxPlayers: 4, genre: 'Cooperative',    length: '60–120 min', complexity: 3.5 },
  { id: 'anachrony',           name: 'Anachrony',                                      year: 2017, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–120 min', complexity: 4.0 },
  { id: 'barrage',             name: 'Barrage',                                        year: 2019, rating: 8.1, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 4.0 },
  { id: 'on-mars',             name: 'On Mars',                                        year: 2020, rating: 8.1, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–180 min', complexity: 4.4 },
  { id: 'eclipse',             name: 'Eclipse: Second Dawn for the Galaxy',            year: 2020, rating: 8.2, minPlayers: 2, maxPlayers: 6,  genre: 'Area Control',    length: '60–200 min', complexity: 3.7 },
  { id: 'dominant-species',    name: 'Dominant Species',                               year: 2010, rating: 7.8, minPlayers: 2, maxPlayers: 6,  genre: 'Area Control',    length: '2–4 hrs',    complexity: 4.2 },
  { id: 'through-the-ages',    name: 'Through the Ages: A New Story of Civilization',  year: 2015, rating: 8.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '2–4 hrs',    complexity: 4.4 },
  { id: 'war-of-the-ring',     name: 'War of the Ring: Second Edition',                year: 2012, rating: 8.3, minPlayers: 2, maxPlayers: 4,  genre: 'Wargame',         length: '3–4 hrs',    complexity: 3.7 },
  { id: 'pandemic-legacy-s1',  name: 'Pandemic Legacy: Season 1',                      year: 2015, rating: 8.6, minPlayers: 2, maxPlayers: 4,  genre: 'Legacy',          length: '60 min',     complexity: 2.8 },
  { id: 'pandemic-legacy-s2',  name: 'Pandemic Legacy: Season 2',                      year: 2017, rating: 8.0, minPlayers: 2, maxPlayers: 4,  genre: 'Legacy',          length: '60 min',     complexity: 2.9 },
  { id: 'descent-2ed',         name: 'Descent: Journeys in the Dark (2nd Edition)',    year: 2012, rating: 7.4, minPlayers: 2, maxPlayers: 5,  genre: 'Dungeon Crawl',   length: '2–3 hrs',    complexity: 2.6 },
  { id: 'imperial-assault',    name: 'Star Wars: Imperial Assault',                    year: 2014, rating: 7.9, minPlayers: 2, maxPlayers: 5,  genre: 'Dungeon Crawl',   length: '90–180 min', complexity: 2.6 },
  { id: 'mansions-madness',    name: 'Mansions of Madness: Second Edition',            year: 2016, rating: 7.9, minPlayers: 1, maxPlayers: 5,  genre: 'Thematic',        length: '2–3 hrs',    complexity: 2.6 },
  { id: 'arkham-horror-lcg',   name: 'Arkham Horror: The Card Game',                   year: 2016, rating: 8.2, minPlayers: 1, maxPlayers: 4,  genre: 'Thematic',        length: '60–120 min', complexity: 3.5 },
  { id: 'arkham-horror-3ed',   name: 'Arkham Horror (Third Edition)',                  year: 2018, rating: 7.7, minPlayers: 1, maxPlayers: 6,  genre: 'Thematic',        length: '2–3 hrs',    complexity: 3.6 },
  { id: 'nemesis',             name: 'Nemesis',                                        year: 2018, rating: 8.0, minPlayers: 1, maxPlayers: 5,  genre: 'Thematic',        length: '90–180 min', complexity: 3.1 },
  { id: 'this-war-of-mine',    name: 'This War of Mine: The Board Game',               year: 2017, rating: 7.9, minPlayers: 1, maxPlayers: 6,  genre: 'Cooperative',     length: '45–120 min', complexity: 3.5 },
  { id: 'tainted-grail',       name: 'Tainted Grail: The Fall of Avalon',              year: 2019, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Thematic',        length: '60–90 min',  complexity: 3.3 },
  { id: 'star-wars-rebellion', name: 'Star Wars: Rebellion',                           year: 2016, rating: 8.3, minPlayers: 2, maxPlayers: 4,  genre: 'Wargame',         length: '3–4 hrs',    complexity: 4.1 },
  { id: 'eldritch-horror',     name: 'Eldritch Horror',                                year: 2013, rating: 7.7, minPlayers: 1, maxPlayers: 8,  genre: 'Thematic',        length: '2–4 hrs',    complexity: 2.9 },
  { id: 'ghost-stories',       name: 'Ghost Stories',                                  year: 2008, rating: 7.5, minPlayers: 1, maxPlayers: 4,  genre: 'Cooperative',     length: '60 min',     complexity: 4.1 },

  // ── Deck Builders ─────────────────────────────────────────────
  { id: 'clank',               name: 'Clank! A Deck-Building Adventure',               year: 2016, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '30–60 min',  complexity: 2.3 },
  { id: 'star-realms',         name: 'Star Realms',                                    year: 2014, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '20 min',     complexity: 1.9 },
  { id: 'ascension',           name: 'Ascension: Deck-Building Game',                  year: 2010, rating: 7.1, minPlayers: 1, maxPlayers: 4,  genre: 'Deck Builder',    length: '30 min',     complexity: 2.1 },
  { id: 'legendary-marvel',    name: 'Legendary: A Marvel Deck Building Game',         year: 2012, rating: 7.7, minPlayers: 1, maxPlayers: 5,  genre: 'Deck Builder',    length: '45 min',     complexity: 2.3 },
  { id: 'harry-potter-hogwarts', name: 'Harry Potter: Hogwarts Battle',                year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '30–60 min',  complexity: 1.8 },
  { id: 'hero-realms',         name: 'Hero Realms',                                    year: 2016, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '20 min',     complexity: 1.7 },
  { id: 'aeons-end',           name: "Aeon's End",                                     year: 2016, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Deck Builder',    length: '60 min',     complexity: 2.9 },

  // ── Cooperative ───────────────────────────────────────────────
  { id: 'the-crew-nine',       name: 'The Crew: The Quest for Planet Nine',            year: 2019, rating: 7.8, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '20 min',     complexity: 2.0 },
  { id: 'the-crew-sea',        name: 'The Crew: Mission Deep Sea',                     year: 2021, rating: 8.0, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '20 min',     complexity: 2.2 },
  { id: 'hanabi',              name: 'Hanabi',                                         year: 2010, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '25 min',     complexity: 2.0 },
  { id: 'flash-point',         name: 'Flash Point: Fire Rescue',                       year: 2011, rating: 7.2, minPlayers: 1, maxPlayers: 6,  genre: 'Cooperative',     length: '45 min',     complexity: 2.0 },
  { id: 'mechs-vs-minions',    name: 'Mechs vs. Minions',                              year: 2016, rating: 8.2, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '60–90 min',  complexity: 2.6 },
  { id: 'magic-maze',          name: 'Magic Maze',                                     year: 2017, rating: 7.1, minPlayers: 1, maxPlayers: 8,  genre: 'Cooperative',     length: '15 min',     complexity: 1.8 },
  { id: 'horrified',           name: 'Horrified',                                      year: 2019, rating: 7.3, minPlayers: 1, maxPlayers: 5,  genre: 'Cooperative',     length: '60 min',     complexity: 1.7 },
  { id: 'sleeping-gods',       name: 'Sleeping Gods',                                  year: 2021, rating: 8.2, minPlayers: 1, maxPlayers: 4,  genre: 'Cooperative',     length: '60–120 min', complexity: 3.2 },
  { id: 'shadows-camelot',     name: 'Shadows Over Camelot',                           year: 2005, rating: 7.1, minPlayers: 3, maxPlayers: 7,  genre: 'Cooperative',     length: '60–90 min',  complexity: 2.3 },
  { id: 'pandemic-hot-zone',   name: 'Pandemic: Hot Zone — North America',             year: 2020, rating: 7.0, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '30 min',     complexity: 1.7 },
  { id: 'micromacro',          name: 'MicroMacro: Crime City',                         year: 2020, rating: 7.4, minPlayers: 1, maxPlayers: 4,  genre: 'Cooperative',     length: '15–45 min',  complexity: 1.3 },
  { id: 'sherlock-consulting',  name: 'Sherlock Holmes: Consulting Detective',          year: 1981, rating: 7.6, minPlayers: 1, maxPlayers: 8,  genre: 'Cooperative',     length: '90 min',     complexity: 2.6 },
  { id: 'escape-curse',        name: 'Escape: Curse of the Temple',                    year: 2012, rating: 7.0, minPlayers: 1, maxPlayers: 5,  genre: 'Cooperative',     length: '10 min',     complexity: 1.8 },
  { id: 'fuse',                name: 'Fuse',                                           year: 2015, rating: 7.0, minPlayers: 1, maxPlayers: 5,  genre: 'Cooperative',     length: '10 min',     complexity: 1.6 },
  { id: 'the-mind',            name: 'The Mind',                                       year: 2018, rating: 7.0, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '20 min',     complexity: 1.0 },

  // ── Party / Social Deduction ──────────────────────────────────
  { id: 'codenames',           name: 'Codenames',                                      year: 2015, rating: 7.6, minPlayers: 2, maxPlayers: 8,  genre: 'Party',           length: '15 min',     complexity: 1.5 },
  { id: 'codenames-pictures',  name: 'Codenames: Pictures',                            year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 8,  genre: 'Party',           length: '15 min',     complexity: 1.5 },
  { id: 'codenames-duet',      name: 'Codenames: Duet',                                year: 2017, rating: 7.7, minPlayers: 2, maxPlayers: 2,  genre: 'Cooperative',     length: '15 min',     complexity: 1.7 },
  { id: 'dixit',               name: 'Dixit',                                          year: 2008, rating: 7.3, minPlayers: 3, maxPlayers: 6,  genre: 'Party',           length: '30 min',     complexity: 1.2 },
  { id: 'mysterium',           name: 'Mysterium',                                      year: 2015, rating: 7.5, minPlayers: 2, maxPlayers: 7,  genre: 'Party',           length: '42 min',     complexity: 1.9 },
  { id: 'wavelength',          name: 'Wavelength',                                     year: 2019, rating: 7.5, minPlayers: 2, maxPlayers: 12, genre: 'Party',           length: '30 min',     complexity: 1.1 },
  { id: 'just-one',            name: 'Just One',                                       year: 2018, rating: 7.6, minPlayers: 3, maxPlayers: 7,  genre: 'Party',           length: '20 min',     complexity: 1.1 },
  { id: 'decrypto',            name: 'Decrypto',                                       year: 2018, rating: 7.7, minPlayers: 3, maxPlayers: 8,  genre: 'Party',           length: '15–45 min',  complexity: 1.8 },
  { id: 'telestrations',       name: 'Telestrations',                                  year: 2009, rating: 7.5, minPlayers: 4, maxPlayers: 8,  genre: 'Party',           length: '30 min',     complexity: 1.2 },
  { id: 'skull',               name: 'Skull',                                          year: 2011, rating: 7.3, minPlayers: 2, maxPlayers: 6,  genre: 'Party',           length: '15–45 min',  complexity: 1.2 },
  { id: 'coup',                name: 'Coup',                                           year: 2012, rating: 7.3, minPlayers: 2, maxPlayers: 6,  genre: 'Social Deduction', length: '15 min',    complexity: 1.6 },
  { id: 'coup-reformation',    name: 'Coup: Reformation',                              year: 2014, rating: 7.3, minPlayers: 2, maxPlayers: 10, genre: 'Social Deduction', length: '15 min',    complexity: 1.7 },
  { id: 'resistance',          name: 'The Resistance',                                 year: 2009, rating: 7.3, minPlayers: 5, maxPlayers: 10, genre: 'Social Deduction', length: '30 min',    complexity: 1.6 },
  { id: 'avalon',              name: 'The Resistance: Avalon',                         year: 2012, rating: 7.6, minPlayers: 5, maxPlayers: 10, genre: 'Social Deduction', length: '30 min',    complexity: 1.7 },
  { id: 'secret-hitler',       name: 'Secret Hitler',                                  year: 2016, rating: 7.5, minPlayers: 5, maxPlayers: 10, genre: 'Social Deduction', length: '45 min',    complexity: 1.6 },
  { id: 'one-night-werewolf',  name: 'One Night Ultimate Werewolf',                    year: 2014, rating: 7.1, minPlayers: 3, maxPlayers: 10, genre: 'Social Deduction', length: '10 min',    complexity: 1.3 },
  { id: 'deception-murder',    name: 'Deception: Murder in Hong Kong',                 year: 2014, rating: 7.5, minPlayers: 4, maxPlayers: 12, genre: 'Social Deduction', length: '20 min',    complexity: 1.5 },
  { id: 'spyfall',             name: 'Spyfall',                                        year: 2014, rating: 7.1, minPlayers: 3, maxPlayers: 8,  genre: 'Social Deduction', length: '15 min',    complexity: 1.1 },
  { id: 'dead-of-winter',      name: 'Dead of Winter: A Cross Roads Game',             year: 2014, rating: 7.4, minPlayers: 2, maxPlayers: 5,  genre: 'Thematic',        length: '60–120 min', complexity: 2.8 },
  { id: 'fury-of-dracula',     name: 'Fury of Dracula (Fourth Edition)',               year: 2015, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Thematic',        length: '2–3 hrs',    complexity: 3.1 },
  { id: 'captain-sonar',       name: 'Captain Sonar',                                  year: 2016, rating: 7.2, minPlayers: 2, maxPlayers: 8,  genre: 'Party',           length: '45–60 min',  complexity: 2.4 },
  { id: 'wits-wagers',         name: 'Wits & Wagers',                                  year: 2005, rating: 6.9, minPlayers: 3, maxPlayers: 7,  genre: 'Party',           length: '25 min',     complexity: 1.1 },
  { id: 'bohnanza',            name: 'Bohnanza',                                       year: 1997, rating: 7.1, minPlayers: 2, maxPlayers: 7,  genre: 'Party',           length: '45 min',     complexity: 1.7 },
  { id: 'cockroach-poker',     name: 'Cockroach Poker',                                year: 2004, rating: 7.1, minPlayers: 2, maxPlayers: 6,  genre: 'Party',           length: '20 min',     complexity: 1.3 },
  { id: 'monikers',            name: 'Monikers',                                       year: 2015, rating: 7.6, minPlayers: 4, maxPlayers: 16, genre: 'Party',           length: '30–60 min',  complexity: 1.1 },
  { id: 'taboo',               name: 'Taboo',                                          year: 1989, rating: 6.3, minPlayers: 4, maxPlayers: 10, genre: 'Party',           length: '20 min',     complexity: 1.0 },
  { id: 'dixit-odyssey',       name: 'Dixit: Odyssey',                                 year: 2011, rating: 7.3, minPlayers: 3, maxPlayers: 12, genre: 'Party',           length: '30 min',     complexity: 1.2 },
  { id: 'anomia',              name: 'Anomia',                                         year: 2010, rating: 6.8, minPlayers: 3, maxPlayers: 6,  genre: 'Party',           length: '30 min',     complexity: 1.1 },
  { id: 'cosmic-encounter',    name: 'Cosmic Encounter',                               year: 2008, rating: 7.4, minPlayers: 3, maxPlayers: 5,  genre: 'Area Control',    length: '60–120 min', complexity: 2.4 },

  // ── Quick / Filler ────────────────────────────────────────────
  { id: 'sushi-go',            name: 'Sushi Go!',                                      year: 2013, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '15 min',     complexity: 1.2 },
  { id: 'sushi-go-party',      name: 'Sushi Go Party!',                                year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 8,  genre: 'Filler',          length: '20 min',     complexity: 1.2 },
  { id: 'love-letter',         name: 'Love Letter',                                    year: 2012, rating: 7.2, minPlayers: 2, maxPlayers: 6,  genre: 'Filler',          length: '20 min',     complexity: 1.3 },
  { id: 'no-thanks',           name: 'No Thanks!',                                     year: 2004, rating: 7.1, minPlayers: 3, maxPlayers: 5,  genre: 'Filler',          length: '20 min',     complexity: 1.1 },
  { id: 'exploding-kittens',   name: 'Exploding Kittens',                              year: 2015, rating: 6.1, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '15 min',     complexity: 1.0 },
  { id: 'coloretto',           name: 'Coloretto',                                      year: 2003, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '30 min',     complexity: 1.3 },
  { id: 'jaipur',              name: 'Jaipur',                                         year: 2009, rating: 7.6, minPlayers: 2, maxPlayers: 2,  genre: 'Filler',          length: '30 min',     complexity: 1.6 },
  { id: 'lost-cities',         name: 'Lost Cities',                                    year: 1999, rating: 7.2, minPlayers: 2, maxPlayers: 2,  genre: 'Filler',          length: '30 min',     complexity: 1.7 },
  { id: 'arboretum',           name: 'Arboretum',                                      year: 2015, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Filler',          length: '30 min',     complexity: 2.2 },
  { id: '6-nimmt',             name: '6 Nimmt!',                                       year: 1994, rating: 7.0, minPlayers: 2, maxPlayers: 10, genre: 'Filler',          length: '45 min',     complexity: 1.2 },
  { id: 'for-sale',            name: 'For Sale',                                       year: 1997, rating: 7.1, minPlayers: 3, maxPlayers: 6,  genre: 'Filler',          length: '20 min',     complexity: 1.3 },
  { id: 'hive',                name: 'Hive',                                           year: 2001, rating: 7.5, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '20 min',     complexity: 2.5 },
  { id: 'hive-pocket',         name: 'Hive Pocket',                                    year: 2010, rating: 7.5, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '20 min',     complexity: 2.5 },
  { id: 'spots',               name: 'Spots',                                          year: 2022, rating: 7.5, minPlayers: 1, maxPlayers: 4,  genre: 'Filler',          length: '20 min',     complexity: 1.3 },
  { id: 'taco-cat',            name: 'Taco Cat Goat Cheese Pizza',                     year: 2019, rating: 6.3, minPlayers: 2, maxPlayers: 8,  genre: 'Party',           length: '10 min',     complexity: 1.0 },
  { id: 'schotten-totten',     name: 'Schotten Totten',                                year: 1999, rating: 7.3, minPlayers: 2, maxPlayers: 2,  genre: 'Filler',          length: '20 min',     complexity: 1.9 },
  { id: 'sushi-roll',          name: 'Sushi Roll',                                     year: 2019, rating: 6.9, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '20 min',     complexity: 1.2 },
  { id: 'kluster',             name: 'Kluster',                                        year: 2020, rating: 7.0, minPlayers: 1, maxPlayers: 4,  genre: 'Dexterity',       length: '15 min',     complexity: 1.1 },

  // ── Wargames / Area Control ───────────────────────────────────
  { id: 'risk-legacy',         name: 'Risk Legacy',                                    year: 2011, rating: 7.6, minPlayers: 3, maxPlayers: 5,  genre: 'Legacy',          length: '60 min',     complexity: 2.3 },
  { id: 'memoir-44',           name: "Memoir '44",                                     year: 2004, rating: 7.2, minPlayers: 2, maxPlayers: 2,  genre: 'Wargame',         length: '30–60 min',  complexity: 2.0 },
  { id: 'kemet',               name: 'Kemet',                                          year: 2012, rating: 7.6, minPlayers: 2, maxPlayers: 5,  genre: 'Area Control',    length: '90 min',     complexity: 2.9 },
  { id: 'blood-rage',          name: 'Blood Rage',                                     year: 2015, rating: 8.0, minPlayers: 2, maxPlayers: 4,  genre: 'Area Control',    length: '60–90 min',  complexity: 2.8 },
  { id: 'inis',                name: 'Inis',                                           year: 2016, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Area Control',    length: '60–90 min',  complexity: 2.7 },
  { id: 'root',                name: 'Root',                                           year: 2018, rating: 8.0, minPlayers: 2, maxPlayers: 4,  genre: 'Area Control',    length: '60–90 min',  complexity: 3.7 },
  { id: 'cry-havoc',           name: 'Cry Havoc',                                      year: 2016, rating: 7.3, minPlayers: 2, maxPlayers: 4,  genre: 'Area Control',    length: '60–120 min', complexity: 2.7 },
  { id: 'axis-allies',         name: 'Axis & Allies',                                  year: 1981, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Wargame',         length: '3+ hrs',     complexity: 3.3 },
  { id: 'imperial-2030',       name: 'Imperial 2030',                                  year: 2009, rating: 7.4, minPlayers: 2, maxPlayers: 6,  genre: 'Area Control',    length: '3 hrs',      complexity: 3.3 },
  { id: 'chaos-old-world',     name: 'Chaos in the Old World',                         year: 2009, rating: 7.7, minPlayers: 3, maxPlayers: 4,  genre: 'Area Control',    length: '120 min',    complexity: 3.6 },
  { id: 'tigris-euphrates',    name: 'Tigris & Euphrates',                             year: 1997, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Area Control',    length: '60–90 min',  complexity: 3.4 },
  { id: 'diplomacy',           name: 'Diplomacy',                                      year: 1959, rating: 6.9, minPlayers: 2, maxPlayers: 7,  genre: 'Wargame',         length: '4–6 hrs',    complexity: 2.7 },

  // ── Abstract ──────────────────────────────────────────────────
  { id: 'chess',               name: 'Chess',                                          year: 1500, rating: 7.7, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '10–60 min',  complexity: 4.0 },
  { id: 'go',                  name: 'Go',                                             year: -200, rating: 7.7, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '30–200 min', complexity: 4.5 },
  { id: 'blokus',              name: 'Blokus',                                         year: 2000, rating: 7.0, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '20 min',     complexity: 1.5 },
  { id: 'quoridor',            name: 'Quoridor',                                       year: 1997, rating: 7.0, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '15 min',     complexity: 1.5 },
  { id: 'santorini',           name: 'Santorini',                                      year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '20 min',     complexity: 1.6 },
  { id: 'azul-summer',         name: 'Azul: Summer Pavilion',                          year: 2019, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30–45 min',  complexity: 1.9 },
  { id: 'azul-stained',        name: 'Azul: Stained Glass of Sintra',                  year: 2018, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30–45 min',  complexity: 2.0 },
  { id: 'tak',                 name: 'Tak: A Beautiful Game',                          year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '20 min',     complexity: 2.5 },
  { id: 'shobu',               name: 'Shobu',                                          year: 2019, rating: 7.5, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '20 min',     complexity: 1.8 },
  { id: 'onitama',             name: 'Onitama',                                        year: 2014, rating: 7.6, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '15–20 min',  complexity: 1.8 },
  { id: 'patchwork-doodle',    name: 'Patchwork Doodle',                               year: 2019, rating: 6.8, minPlayers: 1, maxPlayers: 6,  genre: 'Roll & Write',    length: '20 min',     complexity: 1.5 },

  // ── Dungeon Crawl ─────────────────────────────────────────────
  { id: 'dungeon-lords',       name: 'Dungeon Lords',                                  year: 2009, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 3.0 },
  { id: 'dungeon-petz',        name: 'Dungeon Petz',                                   year: 2011, rating: 7.6, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 3.4 },
  { id: 'sword-sorcery',       name: 'Sword & Sorcery',                                year: 2017, rating: 7.5, minPlayers: 1, maxPlayers: 5,  genre: 'Dungeon Crawl',   length: '60–90 min',  complexity: 3.0 },

  // ── Dexterity ─────────────────────────────────────────────────
  { id: 'jenga',               name: 'Jenga',                                          year: 1983, rating: 6.0, minPlayers: 1, maxPlayers: 99, genre: 'Dexterity',       length: '10 min',     complexity: 1.0 },
  { id: 'crokinole',           name: 'Crokinole',                                      year: 1876, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Dexterity',       length: '30 min',     complexity: 1.3 },
  { id: 'flick-em-up',         name: "Flick 'em Up!",                                  year: 2015, rating: 7.1, minPlayers: 2, maxPlayers: 10, genre: 'Dexterity',       length: '30 min',     complexity: 1.4 },
  { id: 'klask',               name: 'KLASK',                                          year: 2014, rating: 7.3, minPlayers: 2, maxPlayers: 2,  genre: 'Dexterity',       length: '10 min',     complexity: 1.0 },
  { id: 'pitchcar',            name: 'PitchCar',                                       year: 1995, rating: 7.2, minPlayers: 2, maxPlayers: 8,  genre: 'Dexterity',       length: '30 min',     complexity: 1.0 },

  // ── Gateway / Family (additional) ────────────────────────────
  { id: 'camel-up',            name: 'Camel Up',                                       year: 2014, rating: 7.2, minPlayers: 3, maxPlayers: 8,  genre: 'Family',          length: '20–30 min',  complexity: 1.3 },
  { id: 'survive-atlantis',    name: 'Survive: Escape from Atlantis!',                 year: 1982, rating: 7.3, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '45 min',     complexity: 2.0 },
  { id: 'castles-mad-king',    name: 'Castles of Mad King Ludwig',                     year: 2014, rating: 7.5, minPlayers: 1, maxPlayers: 4,  genre: 'Family',          length: '60–90 min',  complexity: 2.1 },
  { id: 'sheriff-nottingham',  name: 'Sheriff of Nottingham',                          year: 2014, rating: 7.3, minPlayers: 3, maxPlayers: 5,  genre: 'Party',           length: '60 min',     complexity: 1.9 },
  { id: 'qwirkle',             name: 'Qwirkle',                                        year: 2006, rating: 7.1, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '45 min',     complexity: 1.5 },
  { id: 'smash-up',            name: 'Smash Up',                                       year: 2012, rating: 7.0, minPlayers: 2, maxPlayers: 4,  genre: 'Filler',          length: '45 min',     complexity: 2.1 },
  { id: 'ticket-nordic',       name: 'Ticket to Ride: Nordic Countries',               year: 2007, rating: 7.6, minPlayers: 2, maxPlayers: 3,  genre: 'Family',          length: '45–75 min',  complexity: 2.0 },
  { id: 'kingdom-builder',     name: 'Kingdom Builder',                                year: 2011, rating: 7.1, minPlayers: 2, maxPlayers: 4,  genre: 'Family',          length: '45 min',     complexity: 1.7 },
  { id: 'taluva',              name: 'Taluva',                                         year: 2006, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '20–45 min',  complexity: 2.5 },
  { id: 'broom-service',       name: 'Broom Service',                                  year: 2015, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Family',          length: '45–75 min',  complexity: 2.1 },
  { id: 'catan-seafarers',     name: 'Catan: Seafarers',                               year: 1997, rating: 7.3, minPlayers: 3, maxPlayers: 4,  genre: 'Family',          length: '75–120 min', complexity: 2.5 },
  { id: 'pandemic-iberia',     name: 'Pandemic: Iberia',                               year: 2016, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Cooperative',     length: '45–60 min',  complexity: 2.3 },
  { id: 'pandemic-cure',       name: 'Pandemic: The Cure',                             year: 2014, rating: 7.5, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '30–45 min',  complexity: 1.9 },

  // ── Mid-weight Euro (additional) ─────────────────────────────
  { id: 'castles-burgundy',    name: 'The Castles of Burgundy',                        year: 2011, rating: 8.0, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–90 min',  complexity: 3.0 },
  { id: 'grand-austria-hotel', name: 'Grand Austria Hotel',                            year: 2015, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.2 },
  { id: 'troyes',              name: 'Troyes',                                         year: 2010, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 3.4 },
  { id: 'lords-waterdeep',     name: 'Lords of Waterdeep',                             year: 2012, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 2.5 },
  { id: 'century-spice',       name: 'Century: Spice Road',                            year: 2017, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '30–45 min',  complexity: 1.8 },
  { id: 'glen-more-2',         name: 'Glen More II: Chronicles',                       year: 2019, rating: 7.7, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.0 },
  { id: 'russian-railroads',   name: 'Russian Railroads',                              year: 2013, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–120 min', complexity: 3.3 },
  { id: 'endeavor-sail',       name: 'Endeavor: Age of Sail',                          year: 2018, rating: 7.7, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 2.7 },
  { id: 'suburbia',            name: 'Suburbia',                                       year: 2012, rating: 7.5, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 2.8 },
  { id: 'alchemists',          name: 'Alchemists',                                     year: 2014, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '120 min',    complexity: 3.6 },
  { id: 'trajan',              name: 'Trajan',                                         year: 2011, rating: 7.8, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.5 },
  { id: 'tikal',               name: 'Tikal',                                          year: 1999, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90 min',     complexity: 2.8 },
  { id: 'bruges',              name: 'Bruges',                                         year: 2013, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 3.2 },
  { id: 'seasons',             name: 'Seasons',                                        year: 2012, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60 min',     complexity: 2.8 },
  { id: 'altiplano',           name: 'Altiplano',                                      year: 2017, rating: 7.2, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 3.1 },
  { id: 'bonfire',             name: 'Bonfire',                                        year: 2020, rating: 7.5, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–100 min', complexity: 3.4 },
  { id: 'carnegie',            name: 'Carnegie',                                       year: 2021, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–180 min', complexity: 3.7 },
  { id: 'forest-shuffle',      name: 'Forest Shuffle',                                 year: 2023, rating: 7.6, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '40–60 min',  complexity: 2.2 },
  { id: 'lacrimosa',           name: 'Lacrimosa',                                      year: 2023, rating: 7.5, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–100 min', complexity: 3.2 },
  { id: 'living-forest',       name: 'Living Forest',                                  year: 2021, rating: 7.4, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '30–45 min',  complexity: 2.2 },
  { id: 'evacuation',          name: 'Evacuation',                                     year: 2023, rating: 8.0, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '90–150 min', complexity: 3.7 },
  { id: 'flamme-rouge',        name: 'Flamme Rouge',                                   year: 2016, rating: 7.4, minPlayers: 2, maxPlayers: 4,  genre: 'Racing',          length: '45 min',     complexity: 1.9 },
  { id: '51st-state',          name: '51st State: Master Set',                         year: 2016, rating: 7.6, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '60–90 min',  complexity: 3.1 },
  { id: 'imperial-settlers',   name: 'Imperial Settlers',                              year: 2014, rating: 7.4, minPlayers: 1, maxPlayers: 4,  genre: 'Euro Strategy',   length: '45–90 min',  complexity: 2.5 },
  { id: 'charterstone',        name: 'Charterstone',                                   year: 2017, rating: 7.4, minPlayers: 2, maxPlayers: 6,  genre: 'Legacy',          length: '45–75 min',  complexity: 2.3 },
  { id: 'dominion-prosperity', name: 'Dominion: Prosperity',                           year: 2010, rating: 7.9, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '30 min',     complexity: 3.0 },

  // ── Heavy Strategy (additional) ───────────────────────────────
  { id: 'food-chain-magnate',  name: 'Food Chain Magnate',                             year: 2015, rating: 7.9, minPlayers: 2, maxPlayers: 5,  genre: 'Euro Strategy',   length: '2–4 hrs',    complexity: 4.4 },
  { id: 'pax-pamir',           name: 'Pax Pamir: Second Edition',                      year: 2019, rating: 8.1, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 4.0 },
  { id: 'paths-of-glory',      name: 'Paths of Glory',                                 year: 1999, rating: 8.0, minPlayers: 2, maxPlayers: 2,  genre: 'Wargame',         length: '3–6 hrs',    complexity: 4.4 },
  { id: 'here-i-stand',        name: 'Here I Stand',                                   year: 2006, rating: 7.8, minPlayers: 2, maxPlayers: 6,  genre: 'Wargame',         length: '6 hrs',      complexity: 4.6 },
  { id: 'john-company',        name: 'John Company: Second Edition',                   year: 2022, rating: 8.0, minPlayers: 1, maxPlayers: 6,  genre: 'Euro Strategy',   length: '3–4 hrs',    complexity: 4.4 },
  { id: 'hegemony',            name: 'Hegemony: Lead Your Class to Victory',           year: 2023, rating: 8.1, minPlayers: 2, maxPlayers: 4,  genre: 'Euro Strategy',   length: '3–4 hrs',    complexity: 4.1 },
  { id: 'age-innovation',      name: 'Age of Innovation',                              year: 2023, rating: 8.1, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '60–150 min', complexity: 4.0 },
  { id: 'dune-imperium-uprising', name: 'Dune: Imperium – Uprising',                   year: 2023, rating: 8.4, minPlayers: 1, maxPlayers: 6,  genre: 'Euro Strategy',   length: '60–120 min', complexity: 3.0 },
  { id: 'snowdonia',           name: 'Snowdonia',                                      year: 2012, rating: 7.4, minPlayers: 1, maxPlayers: 5,  genre: 'Euro Strategy',   length: '75–120 min', complexity: 3.5 },

  // ── Thematic (additional) ─────────────────────────────────────
  { id: 'mice-and-mystics',    name: 'Mice and Mystics',                               year: 2012, rating: 7.4, minPlayers: 1, maxPlayers: 4,  genre: 'Dungeon Crawl',   length: '60–90 min',  complexity: 2.5 },
  { id: 'pandemic-fall-rome',  name: 'Pandemic: Fall of Rome',                         year: 2018, rating: 7.4, minPlayers: 1, maxPlayers: 5,  genre: 'Cooperative',     length: '45–60 min',  complexity: 2.3 },
  { id: 'horrified-monsters',  name: 'Horrified: American Monsters',                   year: 2021, rating: 7.4, minPlayers: 1, maxPlayers: 5,  genre: 'Cooperative',     length: '60 min',     complexity: 1.7 },
  { id: 'aeons-end-war',       name: "Aeon's End: War Eternal",                        year: 2017, rating: 7.9, minPlayers: 1, maxPlayers: 4,  genre: 'Deck Builder',    length: '60 min',     complexity: 2.9 },
  { id: 'eminent-domain',      name: 'Eminent Domain',                                 year: 2011, rating: 7.2, minPlayers: 2, maxPlayers: 4,  genre: 'Deck Builder',    length: '45 min',     complexity: 2.5 },

  // ── Social Deduction (additional) ────────────────────────────
  { id: 'blood-on-clocktower', name: 'Blood on the Clocktower',                        year: 2022, rating: 8.5, minPlayers: 5, maxPlayers: 20, genre: 'Social Deduction', length: '60–120 min', complexity: 2.9 },
  { id: 'mysterium-park',      name: 'Mysterium Park',                                 year: 2020, rating: 7.0, minPlayers: 2, maxPlayers: 6,  genre: 'Party',           length: '30 min',     complexity: 1.4 },
  { id: 'fake-artist',         name: 'A Fake Artist Goes to New York',                 year: 2012, rating: 7.0, minPlayers: 5, maxPlayers: 10, genre: 'Party',           length: '20 min',     complexity: 1.1 },
  { id: 'so-clover',           name: 'So Clover!',                                     year: 2021, rating: 7.5, minPlayers: 3, maxPlayers: 6,  genre: 'Cooperative',     length: '30 min',     complexity: 1.4 },
  { id: 'mind-mgmt',           name: 'MIND MGMT: The Psychic Espionage Game',          year: 2022, rating: 7.9, minPlayers: 2, maxPlayers: 5,  genre: 'Social Deduction', length: '45–75 min',  complexity: 2.4 },
  { id: 'foul-play',           name: 'Suspects: Murder at Guildwood Manor',            year: 2022, rating: 7.2, minPlayers: 1, maxPlayers: 6,  genre: 'Cooperative',     length: '60 min',     complexity: 1.5 },

  // ── Roll & Write (additional) ────────────────────────────────
  { id: 'welcome-to',          name: 'Welcome To...',                                  year: 2018, rating: 7.4, minPlayers: 1, maxPlayers: 100, genre: 'Roll & Write',   length: '25 min',     complexity: 1.5 },
  { id: 'thats-clever',        name: "That's Pretty Clever!",                          year: 2018, rating: 7.7, minPlayers: 1, maxPlayers: 4,  genre: 'Roll & Write',    length: '30 min',     complexity: 1.9 },
  { id: 'qwixx',               name: 'Qwixx',                                          year: 2012, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Roll & Write',    length: '15 min',     complexity: 1.1 },
  { id: 'railroad-ink',        name: 'Railroad Ink: Deep Blue Edition',                year: 2018, rating: 7.3, minPlayers: 1, maxPlayers: 6,  genre: 'Roll & Write',    length: '20–30 min',  complexity: 1.6 },
  { id: 'clever-cubed',        name: 'Clever Cubed',                                   year: 2021, rating: 7.6, minPlayers: 1, maxPlayers: 4,  genre: 'Roll & Write',    length: '30 min',     complexity: 2.0 },
  { id: 'encore',              name: 'Encore!',                                        year: 2016, rating: 7.4, minPlayers: 2, maxPlayers: 6,  genre: 'Roll & Write',    length: '20 min',     complexity: 1.4 },
  { id: 'second-chance',       name: 'Second Chance',                                  year: 2019, rating: 7.1, minPlayers: 1, maxPlayers: 6,  genre: 'Roll & Write',    length: '15–30 min',  complexity: 1.3 },
  { id: 'kingdomino-duel',     name: 'Kingdomino Duel',                                year: 2019, rating: 7.2, minPlayers: 2, maxPlayers: 2,  genre: 'Roll & Write',    length: '20 min',     complexity: 1.5 },

  // ── Abstract (additional) ────────────────────────────────────
  { id: 'tash-kalar',          name: 'Tash-Kalar: Arena of Legends',                   year: 2013, rating: 7.3, minPlayers: 2, maxPlayers: 4,  genre: 'Abstract',        length: '30 min',     complexity: 2.8 },
  { id: 'quarto',              name: 'Quarto!',                                        year: 1991, rating: 7.1, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '20 min',     complexity: 2.3 },
  { id: 'abalone',             name: 'Abalone',                                        year: 1987, rating: 6.7, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '30 min',     complexity: 1.8 },
  { id: 'tzaar',               name: 'Tzaar',                                          year: 2007, rating: 7.5, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '30 min',     complexity: 2.4 },
  { id: 'yinsh',               name: 'YINSH',                                          year: 2003, rating: 7.6, minPlayers: 2, maxPlayers: 2,  genre: 'Abstract',        length: '30 min',     complexity: 2.3 },

  // ── Filler / Quick (additional) ──────────────────────────────
  { id: 'fox-in-forest',       name: 'The Fox in the Forest',                          year: 2017, rating: 7.3, minPlayers: 2, maxPlayers: 2,  genre: 'Filler',          length: '30 min',     complexity: 1.9 },
  { id: 'the-game',            name: 'The Game',                                       year: 2015, rating: 7.0, minPlayers: 2, maxPlayers: 5,  genre: 'Cooperative',     length: '20 min',     complexity: 1.3 },
  { id: 'scout',               name: 'Scout',                                          year: 2019, rating: 7.6, minPlayers: 2, maxPlayers: 5,  genre: 'Filler',          length: '15 min',     complexity: 1.4 },
  { id: 'trio',                name: 'Trio',                                           year: 2023, rating: 7.0, minPlayers: 3, maxPlayers: 6,  genre: 'Filler',          length: '15 min',     complexity: 1.0 },
  { id: 'deep-sea-adventure',  name: 'Deep Sea Adventure',                             year: 2014, rating: 6.8, minPlayers: 2, maxPlayers: 6,  genre: 'Filler',          length: '30 min',     complexity: 1.4 },
  { id: 'cross-clues',         name: 'Cross Clues',                                    year: 2020, rating: 7.0, minPlayers: 2, maxPlayers: 6,  genre: 'Cooperative',     length: '10 min',     complexity: 1.0 },
  { id: 'pairs',               name: 'Pairs',                                          year: 2014, rating: 6.8, minPlayers: 2, maxPlayers: 6,  genre: 'Filler',          length: '15 min',     complexity: 1.1 },
  { id: 'coup-g54',            name: 'Coup: Dystopia (G54)',                           year: 2013, rating: 7.2, minPlayers: 3, maxPlayers: 6,  genre: 'Social Deduction', length: '15 min',    complexity: 1.8 },
  { id: 'fuji-flush',          name: 'Fuji Flush',                                     year: 2016, rating: 6.8, minPlayers: 3, maxPlayers: 8,  genre: 'Filler',          length: '20 min',     complexity: 1.1 },
];
